sudo: required
services:
  - docker 

before_install:
  - docker build -t orensegev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true orensegev/react-test npm test

after_success:
  - docker build -t orensegev/multi-client ./client
  - docker build -t orensegev/multi-server ./server
  - docker build -t orensegev/multi-nginx  ./nginx
  - docker build -t orensegev/multi-worker ./worker
  # Log in to the docekr CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take thosde images and push them to docker hub
  - docker push orensegev/multi-client
  - docker push orensegev/multi-server
  - docker push orensegev/multi-worker
  - docker push orensegev/multi-nginx
